services:
  memory_postgres:
    image: postgres:15
    container_name: memory_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  memory_controller:
    image: memory_controller:test
    build:
      context: .
      dockerfile: ./src/services/MemoryService/Dockerfile
    container_name: memory_controller
    restart: always
    env_file:
      - .env
    depends_on:
      - memory_postgres
    ports:
      - "8001:8000"

  telegram_controller:
    image: telegram_controller:test
    build:
      context: .
      dockerfile: ./src/services/TelegramService/Dockerfile
    container_name: telegram_controller
    restart: always
    env_file:
      - .env
    depends_on:
      - memory_postgres
      - memory_controller
    environment:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      MEMORY_SERVICE_URL: "http://memory_controller:8000"
    ports:
      - "8002:8002"

volumes:
  postgres_data:
